deldog

diff --git a/build b/build
--- a/build
+++ b/build
@@ -1,7 +1,14 @@
 #!/bin/bash
+deldog () {
+	RESULT=$(curl -sf --data-binary @"${1:--}" https://del.dog/documents)  || {
+		echo "ERROR: failed to post document" >&2
+		return 1
+	}
+	KEY=$(printf  "%s\n" "${RESULT}" | cut -d '"' -f6)
+	echo "https://del.dog/${KEY}"
+}
 
 cd /tmp/rom
-
 . build/envsetup.sh
 lunch aosp_mido-user
 export CCACHE_DIR=/tmp/ccache
@@ -10,7 +17,7 @@ export USE_CCACHE=1
 ccache -M 20G
 ccache -o compression=true
 ccache -z
-make aex -j50
+make aex -j50 || cat out/error* > error.txt && deldog error.txt
 #sleep 100m
 #kill $(pidof soong_ui)
 #kill $(pidof make)
